name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test & Publish code coverage (to CodeClimate)
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: <code_climate_reporter_id>
        with:
          coverageCommand: php ./vendor/phpunit/phpunit/phpunit --bootstrap='./vendor/autoload.php' --configuration='./phpunit.xml.dist' --coverage-clover='./build/php/coverage.xml'
          coverageLocations: |
            ${{github.workspace}}/builds/php/*.xml:clover