name: Test and Publish Coverage (CodeClimate)

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: 'composer'

      - name: Install Composer dependencies
        run: composer install

      - name: Install Node dependencies
        run: npm install

      - name: Run Frontend Tests
        run: npm run js:test:coverage

      - name: Run Backend Tests
        run: composer run php:test:coverage

      - name: Publish code coverage (to CodeClimate)
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          # We've already got the coverage files (so don't need to run any tests)
          coverageCommand: echo "Publishing to CodeClimate"
          coverageLocations: |
            ${{github.workspace}}/build/php/*.xml:clover
            ${{github.workspace}}/build/js/clover.xml:clover

      - uses: actions/upload-artifact@v3
        with:
          name: codeclimate-build-files
          path: ${{github.workspace}}