name: Test and Publish Coverage (SonarQube)

on:
  - pull_request
  - push

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: 'composer'

      - name: Install Composer dependencies
        run: composer install

      - name: Install Node dependencies
        run: npm install

      - name: Run Frontend Tests
        run: npm run js:test:coverage

      - name: Run Backend Tests
        run: composer run php:test:coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}